services:
  backend:
    build:
      context: ./Backend
      dockerfile: dockerfile
    ports:
      - "3000:3000"  # Changed to avoid port conflict with host machine
    environment:
      NODE_ENV: production
      PORT: 3000
      # FRONTEND_URL: https://presensepulse-btbwfcgshneeftes.centralindia-01.azurewebsites.net/
      FRONTEND_URL: http://localhost:5173
      JWT_SECRET: c009f72781d65f4a9fcdaee7c9e721d08ff7c6caea02bf5019db21cea90098a1c274b337a53573e4ec5905227e19e2236af4ae7a83ea47530e3e6deb1f42cf32
      DB_HOST: attendancetracker.cluster-cp04ak2iyggj.eu-north-1.rds.amazonaws.com
      DB_USER: root
      DB_PASSWORD: adymysqlrds
      DB_NAME: attendancetracker
      DB_PORT: 3306
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: ./Frontend
      dockerfile: dockerfile
    ports:
      - "5173:80"  # Exposing port 80 from the container to port 5173 on host
    environment:
      # VITE_API_BASE_URL: https://presencepulse-c3a0e8arakhnecax.centralindia-01.azurewebsites.net/ # Backend URL adjusted to 3001
      VITE_API_BASE_URL: http://localhost:3000
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: aws-rds-mysql
    ports:
      - "3306:3306"  # Exposing MySQL on port 3307 on host
    environment:
      MYSQL_ROOT_PASSWORD: adymysqlrds  # Correct MySQL root password setup
      MYSQL_DATABASE: attendancetracker
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
