# Use Node.js 18 base image
FROM node:18

# Set the working directory inside the container
WORKDIR /app

# # Install dependencies and MySQL client from the MySQL 8 repository
# RUN apt-get update && apt-get install -y \
#     gnupg \
#     curl \
#     lsb-release \
#     && curl -sS https://repo.mysql.com/mysql80-community.gpg | tee /etc/apt/trusted.gpg.d/mysql.asc \
#     && echo "deb http://repo.mysql.com/apt/debian/ $(lsb_release -cs) mysql-8.0" | tee /etc/apt/sources.list.d/mysql.list \
#     && apt-get update \
#     && apt-get install -y mysql-client

# Copy package.json and package-lock.json to install dependencies
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the application port
EXPOSE 3000

# Start the application
CMD ["npm", "start"]
