# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - PresencePulse

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: 'your-docker-username'  # Replace with your Docker Hub username
        password: ${{ secrets.DOCKER_PASSWORD }}  # Replace with the secret for Docker password

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/your-docker-username/ady1506/attendancetracker-backend:${{ github.sha }}
        context: .  # Root directory for the build context
        file: ./backend/Dockerfile  # Path to your backend Dockerfile inside the 'backend' folder

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'PresencePulse'
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}  # Azure publish profile secret
        images: 'index.docker.io/your-docker-username/ady1506/attendancetracker-backend:${{ github.sha }}'

# # Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# # More GitHub Actions for Azure: https://github.com/Azure/actions

# name: Build and deploy container app to Azure Web App - PresencePulse

# on:
#   push:
#     branches:
#       - main
#   workflow_dispatch:

# jobs:
#   build:
#     runs-on: 'ubuntu-latest'

#     steps:
#     - uses: actions/checkout@v2

#     - name: Set up Docker Buildx
#       uses: docker/setup-buildx-action@v2

#     - name: Log in to registry
#       uses: docker/login-action@v2
#       with:
#         registry: https://index.docker.io/v1/
#         username: ${{ secrets.AzureAppService_ContainerUsername_7cedc369f3894d88ac7f1834a8cf8afe }}
#         password: ${{ secrets.AzureAppService_ContainerPassword_96a777258953483d9086bf475634fbed }}

#     - name: Build and push container image to registry
#       uses: docker/build-push-action@v3
#       with:
#         push: true
#         tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_7cedc369f3894d88ac7f1834a8cf8afe }}/ady1506/attendancetracker-backend:${{ github.sha }}
#         context: .  # Root directory for the build context
#         file: ./backend/Dockerfile  # Path to your backend Dockerfile inside the 'backend' folder

#   deploy:
#     runs-on: ubuntu-latest
#     needs: build
#     environment:
#       name: 'production'
#       url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

#     steps:
#     - name: Deploy to Azure Web App
#       id: deploy-to-webapp
#       uses: azure/webapps-deploy@v2
#       with:
#         app-name: 'PresencePulse'
#         slot-name: 'production'
#         publish-profile: ${{ secrets.AzureAppService_PublishProfile_d255db36c5214c8b86e2c2995e7ea397 }}
#         images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_7cedc369f3894d88ac7f1834a8cf8afe }}/ady1506/attendancetracker-backend:${{ github.sha }}'
