name: Build and deploy container app to Azure Web App - PresencePulse

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_f87ea78338bb4da4bb2b4323343054db }}
        password: ${{ secrets.AzureAppService_ContainerPassword_9926aadeb51042ae8faedde75455abde }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        context: .  # Set the correct build context
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_f87ea78338bb4da4bb2b4323343054db }}/ady1506/attendancetracker-backend:${{ github.sha }}
        file: ./Dockerfile  # Correct the Dockerfile path if needed

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'PresencePulse'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_b9475aa388314ae3bf3a70ecea089c7f }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_f87ea78338bb4da4bb2b4323343054db }}/ady1506/attendancetracker-backend:${{ github.sha }}'
